# Generated by Django 2.2.2 on 2019-07-26 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_role', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Pay Tickets'), (1, 'User Full Version')], null=True)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Female'), (1, 'Male')], null=True)),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('approved_user', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Not Approved'), (1, 'Approved')], null=True)),
                ('phone_no', models.CharField(blank=True, max_length=50)),
                ('officer_department', models.CharField(blank=True, max_length=100)),
                ('officer_batch_no', models.CharField(blank=True, max_length=50)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Citizen'), (2, 'Officer')], null=True)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_image')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('street_address', models.CharField(blank=True, max_length=200)),
                ('driver_licence_no', models.CharField(blank=True, max_length=50)),
                ('licence_photo', models.ImageField(blank=True, upload_to='licence_photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
