# Generated by Django 2.2.2 on 2019-07-19 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('approved_user', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Not Approved'), (1, 'Approved')], null=True)),
                ('phone_no', models.CharField(blank=True, max_length=50)),
                ('officer_department', models.CharField(blank=True, max_length=100)),
                ('officer_batch_no', models.CharField(blank=True, max_length=50)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Citizen'), (2, 'Officer')], null=True)),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
