# Generated by Django 2.2.2 on 2019-07-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pay_role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Pay Tickets'), (1, 'User Full Version')], null=True),
        ),
    ]
